import type { Category, Shot } from "./types"

export const CATEGORIES: { id: Category | "all"; label: string }[] = [
  { id: "all", label: "All" },
  { id: "opening", label: "Opening" },
  { id: "typography", label: "Typography" },
  { id: "ui-entrance", label: "UI entrance" },
  { id: "camera", label: "Camera" },
  { id: "data", label: "Data" },
  { id: "interaction", label: "Interaction" },
  { id: "transition", label: "Transition" },
  { id: "rhythm", label: "Rhythm" },
  { id: "effects", label: "Effects" },
  { id: "outro", label: "Outro" },
]

export const PRODUCTS = [
  { id: "all", label: "All products" },
  { id: "inspect", label: "Mailgun Inspect" },
  { id: "agent-tools", label: "Agent Tools" },
  { id: "library", label: "Library fillers" },
] as const

export const SHOTS: Shot[] = [
  {
    id: "brand-ink-open",
    name: "brand-ink-open",
    summary:
      "Ink crosshairs draw in, the wordmark stamps letter by letter, a subtitle types on, then the lockup holds and lifts away.",
    use: "Brand open — name the product before any Salesforce chrome appears.",
    duration: "≈ 2.8s (83f)",
    energy: "Low (leave climb room for the feature reel)",
    energyLevel: "low",
    category: "opening",
    tags: ["opening", "typography"],
    products: ["inspect"],
    featured: true,
    params: [
      { name: "Crosshair draw", typical: "vert 0→9f, horiz 8→18f, fade 24→34f", feel: "Must fade — leftover sights steal the wordmark" },
      { name: "Letterpress", typical: "delay 10+i·3, 12f; scale 1.6→1 + blur 6→0", feel: "Opacity + scale + blur is the entrance triad" },
      { name: "Kicker typewriter", typical: "0.7f/char, cursor 2f blink", feel: "Decorative only; body UI typing wants 3f/char" },
      { name: "Brand hold", typical: "46→76f = 1.0s", feel: "Shorter than 1s always gets sent back" },
    ],
    pitfalls: [
      "Hold the wordmark, not a later content card.",
      "Opening energy must stay low so the outro can peak.",
    ],
    sfx: ["transition-soft", "whoosh-fast"],
  },
  {
    id: "paper-title-card",
    name: "paper-title-card",
    summary:
      "A sentence stamps onto paper word by word, highlights one amber italic term, and closes with a short rule.",
    use: "Breathing title between high-energy feature shots.",
    duration: "1.7–1.8s (50–55f)",
    energy: "Low (breathing beat)",
    energyLevel: "low",
    category: "typography",
    tags: ["typography", "transition", "rhythm"],
    products: ["inspect"],
    featured: true,
    params: [
      { name: "Word stamp", typical: "4–5f/word, origin center-bottom", feel: "Amber italic on exactly one keyword" },
      { name: "Rule", typical: "12f draw after last word", feel: "Keep it shorter than the sentence" },
      { name: "Hold", typical: "≥12f after the rule", feel: "Let the line be readable" },
    ],
    pitfalls: ["Two accent words fights the paper-ink system.", "Do not use as the brand open."],
    sfx: ["letterpress", "paper-soft"],
  },
  {
    id: "crane-rise-reveal",
    name: "crane-rise-reveal",
    summary:
      "The camera starts tight on one broken inbox row, rises and pulls back, then reveals a messy QA dashboard filling the frame.",
    use: "Problem open — show the tab jungle before Inspect arrives.",
    duration: "5s (hold 20f + rise 100f + rest 30f)",
    energy: "Mid-high (one continuous move, no punch)",
    energyLevel: "mid",
    category: "opening",
    tags: ["opening", "camera", "data"],
    products: ["inspect"],
    featured: true,
    params: [
      { name: "Start tight", typical: "zoom 2.4 on one failing row", feel: "Must read 'Outlook clipped the CTA'" },
      { name: "Crane", typical: "100f Y-rise + pullback, ease-out", feel: "Decelerate into the full board" },
      { name: "Rest", typical: "≥30f full-frame hold", feel: "No tail drift after settle" },
    ],
    pitfalls: ["Starting wide kills the reveal.", "Do not punch-zoom at the top."],
    sfx: ["whoosh-slow", "camera-rise"],
  },
  {
    id: "spotlight-hero-card",
    name: "spotlight-hero-card",
    summary:
      "A spotlight selects one card, the camera pushes diagonally, the card lifts for two outline passes, then returns to the page.",
    use: "Single-hero product shot — the Inspect LWC inside Salesforce.",
    duration: "≈ 4.6s (82–220f)",
    energy: "Mid (slow, tactile)",
    energyLevel: "mid",
    category: "opening",
    tags: ["opening", "effects", "camera"],
    products: ["inspect"],
    featured: true,
    params: [
      { name: "Pick", typical: "center card at x=960", feel: "Compose for the push, not a random tile" },
      { name: "Camera", typical: "zoom 0.78→2.6 in 16f; rotY 34°", feel: "Side angle reads better than a top-down" },
      { name: "Rise / reseat", typical: "10f overshoot, 54f bob, 18f land", feel: "Lock-to-land ≈ 3.3s" },
      { name: "Outline beam", typical: "lap1 14f bright, lap2 20f dim", feel: "Two laps = scan; one lap = blink" },
    ],
    pitfalls: ["Group dances fail as the first impression.", "Light the hero only — no per-card glints."],
    sfx: ["whoosh-big", "sparkle", "transition-snap"],
  },
  {
    id: "deck-deal-flyin",
    name: "deck-deal-flyin",
    summary:
      "A physical card stack opens the scene, then cards accelerate into a live grid as the camera follows the growing page.",
    use: "Deal 100+ client preview tiles into the Inspect grid.",
    duration: "≈ 2.6s deal (36–113f), optional 2s stack open",
    energy: "High (mid-film climb, not the open)",
    energyLevel: "high",
    category: "ui-entrance",
    tags: ["ui-entrance"],
    products: ["inspect"],
    featured: true,
    params: [
      { name: "Deal", typical: "6–10 cards, 4f stagger, hard accel", feel: "Cards must land in real grid slots" },
      { name: "Camera chase", typical: "follow last card + 8f overshoot", feel: "Hold a half-second on the full board" },
      { name: "Stack open", typical: "optional 62f orbit", feel: "Skip if the previous shot already established paper" },
    ],
    pitfalls: ["Do not open the film on this — energy is too high.", "Floating cards that miss the grid read as stock motion."],
    sfx: ["card-deal", "whoosh-pack"],
  },
  {
    id: "type-and-filter",
    name: "type-and-filter",
    summary:
      "Real UI typing into search, the grid collapsing to one family of clients, then a click punching into a full-resolution preview.",
    use: "Filter Outlook / Gmail / Apple Mail without leaving Salesforce.",
    duration: "≈ 2.5s (118–190f)",
    energy: "Mid (calm after the deal)",
    energyLevel: "mid",
    category: "interaction",
    tags: ["interaction"],
    products: ["inspect"],
    featured: true,
    params: [
      { name: "Type", typical: "3f/character", feel: "Faster feels fake on a real search box" },
      { name: "Converge", typical: "non-matches shrink 12f, matches hold", feel: "Keep at least one readable result" },
      { name: "Click-through", typical: "8f scale + dim others", feel: "Land on a full-res preview, not another grid" },
    ],
    pitfalls: ["0.7f/char is for kickers, not UI.", "Filtering to zero clients is a dead beat."],
    sfx: ["keyboard", "ui-tick", "whoosh-soft"],
  },
  {
    id: "row-embed",
    name: "row-embed",
    summary:
      "Content rows drop from the air, rotateX flatten, and flash an accent seam the instant they seat.",
    use: "Issue list — clipped CTA, dark-mode invert, missing alt.",
    duration: "≈ 2s (12–68f)",
    energy: "Mid",
    energyLevel: "mid",
    category: "ui-entrance",
    tags: ["ui-entrance"],
    products: ["inspect"],
    featured: true,
    params: [
      { name: "Drop", typical: "rotateX 28°→0, 10f, 3f stagger", feel: "Each row must finish flat" },
      { name: "Seam", typical: "accent flash 4f on the bottom edge", feel: "One color — the Inspect amber/pink" },
      { name: "Count", typical: "4–6 rows", feel: "Enough to read, not a log dump" },
    ],
    pitfalls: ["Rows that stay tilted look unfinished.", "Do not stream more than six issues on this beat."],
    sfx: ["embed-tick", "light-seam"],
  },
  {
    id: "list-stack-press",
    name: "list-stack-press",
    summary:
      "List cards fly up from below, compress the growing stack on every landing, and advance a synchronized counter.",
    use: "Client count landing on 100+ as previews stack.",
    duration: "≈ 3s (18–88f)",
    energy: "Mid",
    energyLevel: "mid",
    category: "ui-entrance",
    tags: ["ui-entrance"],
    products: ["inspect"],
    featured: true,
    params: [
      { name: "Fly-up", typical: "from y+140, 8f, 5f stagger", feel: "Each landing squishes the pile" },
      { name: "Press", typical: "scaleY 0.94 → 1.0 with 6f spring", feel: "No press = no weight" },
      { name: "Counter", typical: "digit-roll +1 per card, settle 100+", feel: "Hold the final number ≥15f" },
    ],
    pitfalls: ["Counter that finishes before the last card is a desync.", "Too many cards become noise."],
    sfx: ["stack-hit", "counter-tick"],
  },
  {
    id: "document-typewriter-reveal",
    name: "document-typewriter-reveal",
    summary:
      "A fully typeset document writes itself behind one accent caret, opens both side columns, and drops history entries into the rail.",
    use: "Code analysis / HTML-CSS compatibility notes after the previews.",
    duration: "≈ 3.7s (110f)",
    energy: "Low-mid (let the viewer read)",
    energyLevel: "low",
    category: "typography",
    tags: ["typography", "ui-entrance"],
    products: ["inspect"],
    featured: true,
    params: [
      { name: "Caret", typical: "3f/char, accent block cursor", feel: "The page is already typeset — we only reveal" },
      { name: "Columns", typical: "open after 40% of the body", feel: "History rail pops last" },
      { name: "Hold", typical: "≥15f readable complete state", feel: "Do not cut on the last key" },
    ],
    pitfalls: ["Random-character scramble belongs on glitch-cycle, not here.", "Too fast to read = slideshow."],
    sfx: ["keyboard-long", "paper-open"],
  },
  {
    id: "outro-group-photo-launch",
    name: "outro-group-photo-launch",
    summary:
      "Every element flies in to surround the wordmark, a crane settles, stage light and gold dust turn it into a launch still.",
    use: "Close on 'ship with confidence' after Inspect QA.",
    duration: "≈ 4.8s (145f)",
    energy: "Peak (highest point in the film)",
    energyLevel: "peak",
    category: "outro",
    tags: ["outro"],
    products: ["inspect"],
    featured: true,
    params: [
      { name: "Assemble", typical: "8–12 pieces, 20f inbound", feel: "Pieces must already be familiar from earlier shots" },
      { name: "Crane settle", typical: "rotX 8°→2°, zoom 1.15→1.0", feel: "Stage light after assemble, not before" },
      { name: "Hold", typical: "≥30f wordmark rest", feel: "riser → impact → sparkle, then silence" },
    ],
    pitfalls: ["New unseen assets in the outro feel like a different film.", "Cutting before the 1s hold wastes the peak."],
    sfx: ["riser", "impact", "sparkle"],
  },
  {
    id: "before-after-slider-scrub",
    name: "before-after-slider-scrub",
    summary:
      "A hard split wipes across one email: broken Outlook on the left, Inspect-fixed render on the right.",
    use: "Optional compare beat — one client, two outcomes.",
    duration: "≈ 3.2s (96f)",
    energy: "Mid",
    energyLevel: "mid",
    category: "data",
    tags: ["data", "interaction"],
    products: ["inspect"],
    params: [
      { name: "Scrub", typical: "ease-in-out 36f across, 20f hold each side", feel: "Handle must be obvious" },
      { name: "Labels", typical: "BEFORE / AFTER pinned", feel: "Keep both emails the same campaign" },
    ],
    pitfalls: ["Different emails on each side cheat the compare."],
    sfx: ["slider-tick"],
  },
  {
    id: "page-waterfall-wall",
    name: "page-waterfall-wall",
    summary:
      "Real page captures flow at different speeds across a tilted 3D wall — an endless field of inboxes.",
    use: "Abundance beat for '100+ clients and devices'.",
    duration: "4–6s loop, crop to the paragraph",
    energy: "Mid (flowing display)",
    energyLevel: "mid",
    category: "ui-entrance",
    tags: ["ui-entrance"],
    products: ["inspect"],
    params: [
      { name: "Columns", typical: "3–4 lanes, opposing speeds", feel: "Parallax, not one texture scroll" },
      { name: "Tilt", typical: "rotX 18°, slow push-in", feel: "Keep type barely readable" },
    ],
    pitfalls: ["Illegible mush fails the 'real clients' claim."],
    sfx: ["whoosh-bed"],
  },
  {
    id: "command-palette-summon",
    name: "command-palette-summon",
    summary:
      "A command palette drops from the editor chrome, filters on each key, and lands a Sinch skill as the first hit.",
    use: "Secondary Agent Tools card — IDE + Skills, not the Inspect film.",
    duration: "≈ 3.0s (90f)",
    energy: "Mid",
    energyLevel: "mid",
    category: "interaction",
    tags: ["interaction"],
    products: ["agent-tools"],
    params: [
      { name: "Summon", typical: "12f drop + dimmer 0.35", feel: "Editor chrome stays visible" },
      { name: "Filter", typical: "3f/char on 'sinch'", feel: "First result must be a real skill name" },
    ],
    pitfalls: ["Do not sneak this into the Inspect storyboard."],
    sfx: ["ui-open", "keyboard"],
  },
  {
    id: "blur-slide",
    name: "blur-slide",
    summary:
      "Title words rise into place as vertical offset, blur, and opacity share one ease; the subtitle follows.",
    use: "Library filler — generic title card.",
    duration: "≈ 3.8s (114f)",
    energy: "Low",
    energyLevel: "low",
    category: "typography",
    tags: ["typography"],
    products: ["library"],
    params: [
      { name: "Word ease", typical: "y 40→0 + blur 10→0, 3.5f gap", feel: "One shared outCubic" },
    ],
    pitfalls: ["Stagger that is too long reads as a slide deck."],
    sfx: ["whoosh-soft"],
  },
  {
    id: "card-stack",
    name: "card-stack",
    summary:
      "Eight cards spring up into a pile, then the pile fans into a 3D arc.",
    use: "Library filler — Notion / Figma-style card pile.",
    duration: "≈ 4.2s (126f)",
    energy: "Mid-high",
    energyLevel: "high",
    category: "ui-entrance",
    tags: ["ui-entrance"],
    products: ["library"],
    params: [
      { name: "Spring in", typical: "8 cards, 6f stagger", feel: "Fan only after the pile exists" },
      { name: "Fan", typical: "8° / 34px / −1 z per card", feel: "One group move, not eight solos" },
    ],
    pitfalls: ["Fanning while cards are still arriving is busy."],
    sfx: ["card-deal"],
  },
  {
    id: "draw-svg-trace",
    name: "draw-svg-trace",
    summary:
      "An ink stroke traces an element outline, closes with a dark flash, and hands focus to the revealed content.",
    use: "Library filler — circle a UI control.",
    duration: "3–4s (stroke 40f + flash 16f + hold ≥35f)",
    energy: "Mid",
    energyLevel: "mid",
    category: "ui-entrance",
    tags: ["ui-entrance", "typography"],
    products: ["library"],
    params: [
      { name: "Stroke", typical: "40f dashoffset, nib visible", feel: "Close the path before the flash" },
    ],
    pitfalls: ["Leaving the stroke on after the flash splits focus."],
    sfx: ["ink-draw", "flash"],
  },
  {
    id: "fracture",
    name: "fracture",
    summary:
      "A 5×5 tile field ripples into a poster, holds, then explodes off-screen.",
    use: "Library filler — high-energy open you would not use on Inspect.",
    duration: "≈ 5.2s (156f)",
    energy: "High",
    energyLevel: "high",
    category: "opening",
    tags: ["opening"],
    products: ["library"],
    params: [
      { name: "Assemble", typical: "center-out 2.6s", feel: "Hold 1s before the shatter" },
    ],
    pitfalls: ["Too loud for an Inspect brand open."],
    sfx: ["impact", "glass"],
  },
  {
    id: "letterspace-materialize",
    name: "letterspace-materialize",
    summary:
      "Every letter of a widely tracked wordmark draws itself in parallel and finishes on the same frame.",
    use: "Library / Agent Tools wordmark alternate.",
    duration: "3–4s",
    energy: "Low",
    energyLevel: "low",
    category: "opening",
    tags: ["opening", "typography"],
    products: ["agent-tools", "library"],
    params: [
      { name: "Parallel draw", typical: "~50f, all glyphs start/end together", feel: "No left-to-right cascade" },
    ],
    pitfalls: ["Cascading letters become a different card."],
    sfx: ["ink-draw"],
  },
  {
    id: "list-reveal",
    name: "list-reveal",
    summary:
      "Menu rows scale in with a faint overshoot while the whole list drifts slowly upward.",
    use: "Library filler — settings / Slack sidebar.",
    duration: "≈ 3.6s (108f)",
    energy: "Low",
    energyLevel: "low",
    category: "ui-entrance",
    tags: ["ui-entrance"],
    products: ["library"],
    params: [
      { name: "Item", typical: "0.09 stagger, outBack", feel: "Drift is a second independent layer" },
    ],
    pitfalls: ["Locking drift to each item looks mechanical."],
    sfx: ["ui-tick"],
  },
  {
    id: "carousel-3d",
    name: "carousel-3d",
    summary:
      "Eight cards sit on a circular ring and complete one revolution while billboarding toward camera.",
    use: "Library filler — product tour.",
    duration: "≈ 5.6s (168f)",
    energy: "Mid (steady loop)",
    energyLevel: "mid",
    category: "ui-entrance",
    tags: ["ui-entrance"],
    products: ["library"],
    params: [
      { name: "Orbit", typical: "radius 190px, one turn", feel: "Never show a mirrored back face" },
    ],
    pitfalls: ["Upside-down cards break the billboard."],
    sfx: ["whoosh-bed"],
  },
  {
    id: "ai-stream-response",
    name: "ai-stream-response",
    summary:
      "An assistant panel lands a readable summary, then evidence rows stream in and settle on a complete state.",
    use: "Library filler — agent panel, not the Inspect hero.",
    duration: "4–5s",
    energy: "Mid-high",
    energyLevel: "high",
    category: "interaction",
    tags: ["interaction"],
    products: ["library"],
    params: [
      { name: "Summary first", typical: "readable line before any row", feel: "Complete-state hold ≥15f" },
    ],
    pitfalls: ["Log-spam with no summary is the anti-pattern."],
    sfx: ["stream-tick"],
  },
  {
    id: "word-relay-filmstrip",
    name: "word-relay-filmstrip",
    summary:
      "A filmstrip of page cards steps vertically while a serif word relay swaps only its verb.",
    use: "Library filler — editorial rhythm.",
    duration: "5–7s",
    energy: "Low-mid",
    energyLevel: "low",
    category: "typography",
    tags: ["typography", "ui-entrance"],
    products: ["library"],
    params: [
      { name: "Relay", typical: "1.5–2s per verb", feel: "Card center lines up with the word block" },
    ],
    pitfalls: ["Scrolling the strip without a word change is wallpaper."],
    sfx: ["film-click"],
  },
  {
    id: "glitch-cycle",
    name: "glitch-cycle",
    summary:
      "Status phrases cycle in one monospace slot with RGB split and jitter, then lock clean.",
    use: "Library filler — status line.",
    duration: "≈ 5.6s (168f)",
    energy: "Mid-high",
    energyLevel: "high",
    category: "typography",
    tags: ["typography"],
    products: ["library"],
    params: [
      { name: "Cycle", typical: "4 phrases × 42f, last phrase clean", feel: "End on a readable lock" },
    ],
    pitfalls: ["Endless noise with no lock is unusable in a promo."],
    sfx: ["glitch"],
  },
  {
    id: "grain-dissolve",
    name: "grain-dissolve",
    summary:
      "The last frame of the film dissolves into paper grain and a small wordmark.",
    use: "Optional end card if the group-photo outro is too large.",
    duration: "≈ 2.2s",
    energy: "Low",
    energyLevel: "low",
    category: "outro",
    tags: ["outro"],
    products: ["library"],
    params: [
      { name: "Grain", typical: "18f dissolve, 40f hold", feel: "Do not introduce a new color" },
    ],
    pitfalls: ["A second brand lockup after the peak outro doubles the ending."],
    sfx: ["film-tail"],
  },
]

export function shotById(id: string) {
  const shot = SHOTS.find((item) => item.id === id)
  if (!shot) throw new Error(`Unknown shot: ${id}`)
  return shot
}
